In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#head
cutoff = 55
n_layers = 6

In [ ]:
def gen_2d_dome(n_layers):

    T = [1] + [(x+1)*10 for x in range(n_layers-1)]
    R = [0.0] + [(x+1)*0.1 for x in range(n_layers-1)]
    T = [int(np.ceil(x*0.6)) for x in T]
    R = [x*20 for x in R]

    def rtpairs(r, n):
        for i in range(len(r)):
            for j in range(n[i]):
                yield r[i]*1, j*(2 * np.pi / n[i])
    points = []
    ppoints = []
    ppoints_temp = []
    for r, t in rtpairs(R, T):
        x, y = r * np.cos(t), r * np.sin(t)
        if y>=-0:
            ppoints_temp.append([r,t])
            points.append([x,y])
    points = np.round([[x/12*255+255,y/12*255+255] for x, y in points], 2)
    ppoints = np.round(ppoints_temp,3)

    xpoints = []
    ypoints = []
    xpoints = (points[:, 0])
    ypoints = (points[:, 1])

    print(points)

    return points

In [ ]:
def get_neib_mx(cutoff, points):

    neib_mx = []
    # linalg.norm
    neib_mx = np.zeros((len(points), len(points)))
    for i, pt1 in enumerate(points):
        for j in range(i+1, len(points)):
            pt2 = points[j]
            dis = np.linalg.norm(pt2-pt1)
            if dis < cutoff:
                neib_mx[i,j] = 1
                neib_mx[j,i] = 1

    # old ver
    cutoff=55
    neib_mxold = np.zeros((len(points), len(points)))
    for i, pt1 in enumerate(points):
        for j in range(i+1, len(points)):
            pt2 = points[j]
            if sum(((pt1 - pt2) ** 2)) < cutoff ** 2:
                neib_mxold[i,j] = 1
                neib_mxold[j,i] = 1


    # neib_mx == old neib
    print(np.all(neib_mxold == neib_mx))

    return neib_mx

In [ ]:
points = gen_2d_dome(n_layers=6)
neib_mx = get_neib_mx(cutoff, points)
print(neib_mx)

[[255.   255.  ]
 [297.5  255.  ]
 [276.25 291.81]
 [233.75 291.81]
 [212.5  255.  ]
 [340.   255.  ]
 [328.61 297.5 ]
 [297.5  328.61]
 [255.   340.  ]
 [212.5  328.61]
 [181.39 297.5 ]
 [170.   255.  ]
 [382.5  255.  ]
 [374.81 298.61]
 [352.67 336.96]
 [318.75 365.42]
 [277.14 380.56]
 [232.86 380.56]
 [191.25 365.42]
 [157.33 336.96]
 [135.19 298.61]
 [127.5  255.  ]
 [425.   255.  ]
 [419.21 299.  ]
 [402.22 340.  ]
 [375.21 375.21]
 [340.   402.22]
 [299.   419.21]
 [255.   425.  ]
 [211.   419.21]
 [170.   402.22]
 [134.79 375.21]
 [107.78 340.  ]
 [ 90.79 299.  ]
 [ 85.   255.  ]
 [467.5  255.  ]
 [462.86 299.18]
 [449.13 341.43]
 [426.92 379.9 ]
 [397.19 412.92]
 [361.25 439.03]
 [320.67 457.1 ]
 [277.21 466.34]
 [232.79 466.34]
 [189.33 457.1 ]
 [148.75 439.03]
 [112.81 412.92]
 [ 83.08 379.9 ]
 [ 60.87 341.43]
 [ 47.14 299.18]
 [ 42.5  255.  ]]
True
[[0. 1. 1. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 1